name: python-hello-world

on:
  push:
    branches:
      - main
    paths:
      - 'python-hello-world/**'
  repository_dispatch:
    types: [ec2-created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: '{{defaultContext}}:python-hello-world'
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python-hello-world:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/python-hello-world:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy setup files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.ACTIONS_SA_KEY }}
          source: 'python-hello-world/compose.yaml,python-hello-world/schema.sql'
          target: '~'

      - name: Setup and execute the application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.ACTIONS_SA_KEY }}
          script: |
            # Get into the working directory
            cd ~/python-hello-world

            # Create the database schema
            mysql -h "${{ secrets.RDS_HOST }}" -u "${{ secrets.RDS_MASTER_USER }}" -p"${{ secrets.RDS_MASTER_PASS }}" < schema.sql

            # Create the application user
            mysql -h "${{ secrets.RDS_HOST }}" -u "${{ secrets.RDS_MASTER_USER }}" -p"${{ secrets.RDS_MASTER_PASS }}" -e "
              CREATE USER IF NOT EXISTS '${{ secrets.RDS_APP_USER }}'@'%' IDENTIFIED BY '${{ secrets.RDS_APP_PASS }}';
              GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO '${{ secrets.RDS_APP_USER }}'@'%';
              FLUSH PRIVILEGES;
            "

            # Cleanup the schema file
            rm -f schema.sql

            # Pull the latest image and (re)start the application
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python-hello-world:latest
            docker compose down
            docker compose up -d --force-recreate

            # Cleanup dangling images
            DANGLING_IMAGES=$(docker images -f dangling=true -q)
            if [ -n "$DANGLING_IMAGES" ]; then
              docker rmi $DANGLING_IMAGES
            fi
